name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      env:
        GOOGLE_APPLICATION_CREDENTIALS_RAW: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        TEST_CREDENTIALS: ${{ secrets.TEST_CREDENTIALS }}
      run: |
        hostname -I
        hostname -A
        echo "preparing test credentials"
        echo -n "$TEST_CREDENTIALS" > env.txt
        echo >> env.txt
        echo "GOOGLE_APPLICATION_CREDENTIALS=$(echo $GOOGLE_APPLICATION_CREDENTIALS_RAW)" >> env.txt
        cat env.txt
        docker run -i --env-file=env.txt alpine env

    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path:  env.txt
