name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

#     - name: Set up Go 1.12
#       uses: actions/setup-go@v1
#       with:
#         go-version: 1.12
#       id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      env:
        KEY_RAW: ${{ secrets.KEY_RAW }}
        TEST_CREDENTIALS: $ {{ secrets.TEST_CREDENTIALS }}
      run: |
        echo $TEST_CREDENTIALS > env.txt
        # echo $KEY_RAW >> env.txt
        echo "K2=$(echo -n $KEY_RAW)" >> env.txt
        # echo "K3=$KEY_RAW" >> env.txt
        cat env.txt
        docker run -i --env-file=env.txt alpine env
